[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  # Sets a custom directory for Netlify Functions
  directory = ".output/"

  # Specifies `esbuild` for functions bundling
  node_bundler = "esbuild"
