[build]
  publish = "dist"
  command = "npm run deploy"

[functions]
  # Sets a custom directory for Netlify Functions
  directory = ".netlify/functions"
  node_bundler = "none"
  included_files = [".netlify/functions/**"]
